# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'iMovieDB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iMovieDB
  pod 'Alamofire'  
  pod 'Kingfisher'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'

end
