# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'iMovieDB' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iMovieDB
  pod 'Alamofire'  
  pod 'Kingfisher'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.1'
        end
    end
end
